#
# Display sensor property names
#
template st:header {
    format  {
        <format/header.html>
        group { format { "<th>%s. %s</th>" st:number() us:pretty(?pname)  } }
    }
}
where {
   values ?pname { unnest(st:get(st:plist)) }
}

