#
# SPARQL Template Transformation 
# Generate a HTML hypertext navigator on top of Linked Data
# Start template
#
# Olivier Corby - Wimmics INRIA I3S - 2018
#
template st:start {

  st:call-template(st:main)
  
}
where {
    # compute and record property list
    bind (st:set(st:plist, us:init())  as ?i)
}

